-- Public click-tracking (/r/[code]) and unsubscribe (/unsubscribe/[token],
-- /api/unsubscribe/[token]) routes run on the server and use the Supabase
-- service-role client (which bypasses RLS) to look up and update rows.
--
-- The anon role therefore gets NO SELECT or UPDATE access to
-- `review_requests`, `businesses`, or `customers` — the owner-level
-- policies created in 00001_initial_schema.sql are sufficient for the
-- authenticated app shell.
--
-- Why this is safe:
--  - Short codes are 8-char random strings (62^8 ~ 2e14), HMAC-signed
--    tokens protect unsubscribe links, and all database access for these
--    routes happens server-side using the service role.
--  - Allowing direct anon access would let anyone with the anon key
--    enumerate every business, every customer, and every review request,
--    which is an unacceptable data leak.
--
-- This migration intentionally creates nothing — its purpose is to document
-- the decision.
SELECT 1;
